### ISSUE TITLE
Problem with cloning tags after multiple saving content

### ISSUE THREAD

**Issue by ruznopace** [devlabnet/SlideShow#14]
Initial code after first saving generated slideshow code in database is ok. After changing some content around but not touching slideshow, slideshow code after 2nd savings have some duplicate tags. 

After 2nd saving, duplicated divs are: ad-forward, ad-back, ad-info, ad-slideshow-controls ad-slideshow-running. The problem is that jquery.ad-gallery.min.js is generating that divs everytime when editing mode is turns, but old divs are saved when they were generated in frist time. And after every other savings divs are multiplying.

Code of duplicated tags:

<div class="ad-gallery" id="ad-gallery_cke_582l5btb_slideShow" contenteditable="false">
	<div class="ad-image-wrapper" style="height: 370px;" contenteditable="false">
		<div style="width: 663px; height: 370px; top: 0px; left: 0px;" class="ad-image"><img src="http://localhost/department/uploads/ck_editor/images/architecture_design-1024x768.jpg" height="370" width="663"></div>
		<img style="display: none;" class="ad-loader" src="http://localhost/department/js/ckeditor/plugins/slideshow/3rdParty/ad-gallery/loader.gif">
		<div class="ad-next"><div style="opacity: 0.7;" class="ad-next-image"></div></div>
		<div style="height: 370px;" class="ad-prev"><div style="opacity: 0.7; display: none;" class="ad-prev-image"></div></div>
	</div>

	<div class="ad-controls" style="display: none;" contenteditable="false">&nbsp;
		<p class="ad-info">1 / 2</p>
		<div class="ad-slideshow-controls ad-slideshow-running"><span class="ad-slideshow-start">Start</span><span class="ad-slideshow-stop">Stop</span><span class="ad-slideshow-countdown" style="">(5)</span></div>
		<p class="ad-info">2 / 2</p><div class="ad-slideshow-controls ad-slideshow-running"><span class="ad-slideshow-start">Start</span><span class="ad-slideshow-stop">Stop</span><span style="" class="ad-slideshow-countdown">(5)</span></div>
	</div>

	<div class="ad-nav" style="display: block;" contenteditable="false">
		<div style="opacity: 1;" class="ad-back"></div>
		<div class="ad-back" style="opacity: 1;">&nbsp;</div>
		<div class="ad-thumbs" contenteditable="false">
		<ul style="width: 277px;" class="ad-thumb-list" contenteditable="false">
			<li contenteditable="false"><a class="" href="http://localhost/department/uploads/ck_editor/images/7ea5da96cde15fbc85bd3652f162271d.jpg" contenteditable="false"><img alt="" src="http://localhost/department/uploads/ck_editor/images/7ea5da96cde15fbc85bd3652f162271d.jpg" style="opacity: 0.7;" title="" contenteditable="false" height="28" width="50"></a></li>
			<li contenteditable="false"><a class="ad-active" href="http://localhost/department/uploads/ck_editor/images/architecture_design-1024x768.jpg" contenteditable="false"><img alt="" src="http://localhost/department/uploads/ck_editor/images/architecture_design-1024x768.jpg" style="opacity: 1;" title="" contenteditable="false" height="28" width="50"></a></li>
		</ul>
		</div>
		<div class="ad-forward" style="opacity: 1;">&nbsp;</div>
		<div style="opacity: 1;" class="ad-forward"></div>
	</div>
</div>

**Comment by cricri042** [comment]
Hi,
Can you try the last version, as I did some fix !!
  --Christian
