### ISSUE TITLE
Drupal + CKEditor slideshow

### ISSUE THREAD

**Issue by skippednote** [devlabnet/SlideShow#15]
Hi,

I'm using Drupal 7 with CKEditor + Slideshow addon and I'm facing issues with IE10 and below versions. The active images in the slideshow doesn't show up in IE, however it works fine in other browsers.

The markup of the image doesnt load for IE10 or below and radomly there are inline styles on the image wrapper with width and height of 0px. 

http://i.imgur.com/5fatb6i.png

**Comment by cricri042** [comment]
Hi ,
Can you try the last version, as I did some fix !!
  --Christian
