### ISSUE TITLE
ckeditor doesn't load, with en javascript error

### ISSUE THREAD

**Issue by sander-martijn** [devlabnet/SlideShow#16]
I have installed the Slideshow and enabled the plugin. Now CKEditor doesn't load at all, just a blank white box. 

When opening the javascript console I see:
Uncaught ReferenceError: en is not defined

Line number is 207 which contains the following:
en = { slideshow : en} ;

**Comment by sander-martijn** [comment]
oh and btw I did add the language config item

**Comment by cricri042** [comment]
Hi sander,
Can you try the last version, as I did some fix !!
  --Christian
