### ISSUE TITLE
Ckeditor SlideShow Plugin in OpenCart. Some troubles with layout of thumbnails.

### ISSUE THREAD

**Issue by ltraveler** [devlabnet/SlideShow#17]
I have a projcet www.tendre.me.
Here is an a blog post:
[Runa-Simi Alpaca Store](http://tendre.me/alpaca-rundown)

As you see on a slideshow layout the image is not on a middle it is like more to the right arrow icon, I guess it is should be between.
More over if I will switch on the thumbnail layout, the width of the page becoming much bigger than it should be, so I just switched off the thumbnails layout but it is definitely a bug. There is a video that:
[Runa-Simi Alpaca Store CkEditor SlideShow Plugin Bug](https://youtu.be/uctk_Sem7RY)

**Comment by cricri042** [comment]
Hi,
Yep it was some problems, I've put online in "ckeditor.com" a new version of the slideshow (version 1.07) can you get it from there and check if the problem is still there.
Please, get the version from "ckeditor" website as I didn't yet update the data on GitHub.
Cordially

 --Christian
PS: please give me feedback, so I will update (if ok) data in GitHub.

**Comment by ltraveler** [comment]
I downloaded latest version and the problem still exists. 
http://tendre.me/alpaca-rundown
Check it please. I leaved it with thumbnail on option.

**Comment by ltraveler** [comment]
I used latest version of FireFox

**Comment by ltraveler** [comment]
In Chrome the width is good but I can not see a main image only thumbnails

**Comment by cricri042** [comment]
Hi,
Just checked your web page, and I don't see any problem !!
On my side everything is ok in chrome, firefox, edge and maxthon !!

  --Christian

**Comment by ltraveler** [comment]
Yes that is right! Thank you! I think there was a cache problem but there is one more but. If you add for example 3 pictures to your gallery then add title and description for example for the first one when you are going to the second one the description and title can not be saved or the description from the first one somehow copying to the second one. And every time I should click ok then open the window again select the second foto add title and description and so on...

**Comment by cricri042** [comment]
Hi,
Can you check if this problem still occurs in the last version, I di some change and now it will be  (hopefully) ok !!.
--Christian

**Comment by ltraveler** [comment]
Thank you very much Christian! Everything works perfect now! You've made wonderful extension!

**Comment by cricri042** [comment]
Hi Itraveler,
Nice to hear !!
If you like it, just go to "http://ckeditor.com/addon/slideshow" and rate it !! lol
Have a nice day

--Christian

**Comment by ltraveler** [comment]
I will be happy to rate it! But please could you remain me what kind of email address I used to contact you and give you an ftp access. Please if you can upload a txt file with your email address and also with mine which I used to contact you through the ckeditor.com website. Sorry I just lost the name of this address. Thank you very much in advance!

**Comment by ltraveler** [comment]
Crisstian, I rate it. Thanks! For the future how to contact you by email?..

**Comment by cricri042** [comment]
Hi Itraveler,
Thanks, for the e-mail just use slideshow@devlabnet.eu , by this way I know that's relating to slideshow component !!
Have a nice day.

  --Christian
