### ISSUE TITLE
Installing on yii2

### ISSUE THREAD

**Issue by loy123** [devlabnet/SlideShow#22]
How to install SlideShow for ckeditor on yii2 Framework?

**Comment by cricri042** [comment]
Hi Loy,
I don't know yii2, but if the ckeditor plugin for yii2 exists, an if you have ckeditor running, adding the slideshow dis just adding another plugin to ckeditor, I guess it will work !!
What kind of problem do you have ?

  --Christian

**Comment by loy123** [comment]
I copied slideshow to plugin folder in ckeditor, and copied CKEDITOR.config.extraPlugins = 'slideshow'; to config.js file. 
![a1](https://cloud.githubusercontent.com/assets/17383034/13700101/63346d8e-e7b1-11e5-8169-e80bd65d74d7.png)

**Comment by loy123** [comment]
My problem : The Icon slideshow not show on Ckeditor Toolbar

**Comment by cricri042** [comment]
Hi,
Looks strange, do you get any errors in the javascript console ? did you well clear your navigator cache ?
If yes, ca
