### ISSUE TITLE
no slideshow - wrong calculate left on .ad-image

### ISSUE THREAD

**Issue by santaclaus21** [devlabnet/SlideShow#8]
I am trying to use this gallery. Tis is almost great, but I've got some problems. Depending of website contents (main css) sometimes I can see just thumbs + empty container - but no images. 

Tracking that I've found a problem. When I set 

```
.ad-image {
  cursor: pointer;
  left: 0 !important;
}
```

Images are show - but aligned to left. Before that I can see in console there is left~=1365px. I would like to center it

![slide1](https://f.cloud.github.com/assets/1121662/2435489/53ae403a-adc8-11e3-8bfc-0e5859895938.jpg)

**Comment by cricri042** [comment]
Hi,
Can you try the last version, as I did some fix !!
  --Christian
