### ISSUE TITLE
ACF vs SlideShow source

### ISSUE THREAD

**Issue by santaclaus21** [devlabnet/SlideShow#9]
The next one problem is ACF. When I compile CKEditor (last) with SlideShow, aftert first add gallery - everything is pretty fine. But second one open website source by ckeditor - I can see that lot of code is lost.

f.e. contenteditable="false" data-animspeedid="500" data-autostartid="true" data-openonclickid="true"... 

I can see only id and class on div elements (according to my allowcontent). Additional all script tag are lost. 

I am not pretty sure, but I was wondering if slideshow can modify ACF exceptions while is compiled by CKE Builder? - Would you like to check that?

**Comment by cricri042** [comment]
Hi,
Can you try the last version, as I did some fix !!
  --Christian
